py.test
============================= test session starts ==============================
platform linux -- Python 3.6.8, pytest-4.1.0, py-1.7.0, pluggy-0.8.1
rootdir: /home/luismiguel/bitbucket/py_pol, inifile: pytest.ini
collected 105 items

tests/test_drawing.py ...........                                        [ 10%]
tests/test_jones_matrix.py ............                                  [ 21%]
tests/test_jones_matrix_parameters.py ......                             [ 27%]
tests/test_jones_vector.py .............                                 [ 40%]
tests/test_jones_vector_parameters.py ..                                 [ 41%]
tests/test_mueller.py .......................                            [ 63%]
tests/test_mueller_check_analysis.py ............                        [ 75%]
tests/test_mueller_parameters.py ...............                         [ 89%]
tests/test_stokes.py .......                                             [ 96%]
tests/test_stokes_parameters.py .                                        [ 97%]
tests/test_utils.py ...                                                  [100%]

=============================== warnings summary ===============================
tests/test_drawing.py::TestDrawing::test_ellipse_stokes_probabilities
  /home/luismiguel/.local/lib/python3.6/site-packages/matplotlib/contour.py:1243: UserWarning: No contour levels were found within the data range.
    warnings.warn("No contour levels were found"

tests/test_mueller_parameters.py::TestMueller_parameters::test_inhomogeneity
  /home/luismiguel/bitbucket/py_pol/py_pol/mueller.py:1581: RuntimeWarning: invalid value encountered in cdouble_scalars
    ) / np.sqrt(m00 + M[1, 1] + M[1, 0] + M[0, 1])

-- Docs: https://docs.pytest.org/en/latest/warnings.html
=================== 105 passed, 2 warnings in 3.05 seconds ====================
